--table which will have the LNDC information at an order level
CREATE OR REPLACE TABLE  GA360_DEV.LNDC_ORDER_LEVEL_DATA AS
(
    SELECT *,
        CASE    WHEN SALESCHANNEL = 'WB' THEN ECOMM_ANALYTICS.ECOMM_KPI_DEV.MAP_TO_CHANNEL_L1(SOURCE,MEDIUM,CAMPAIGN,TOPLEVELCATEGORY,ORDERTYPE) 
                ELSE SALESCHANNEL 
                END AS CHANNEL_L1,
        CASE    WHEN ORDERS = 1 THEN 'INITIAL'
                WHEN ORDERS IN (0, -1) THEN 'UPDATE'
                ELSE NULL
                END AS BBSTATUS,
        FROM
        (
        SELECT
            BBB.ORIGSYSREF,
            BBB.ORDERNUMBER,
            UPPER(TRIM(BBB.COUNTRY)) AS COUNTRY,
            BBB.BOOKINGDATE,
            BBB.ORDERTYPE,
            BBB.KEYCODE,
            BBB.SALESCHANNEL,
            ---For cases where order id is present in both union view with channel<> WEB and in ga3_ga4 ignore the SMC params
            CASE WHEN BBB.SALESCHANNEL = 'WB' THEN LOWER(TRIM(GA.GA_SOURCE)) ELSE NULL END AS SOURCE,
            CASE WHEN BBB.SALESCHANNEL = 'WB' THEN LOWER(TRIM(GA.GA_MEDIUM)) ELSE NULL END AS MEDIUM,
            CASE WHEN BBB.SALESCHANNEL = 'WB' THEN LOWER(TRIM(GA.GA_CAMPAIGN)) ELSE NULL END AS CAMPAIGN,
            CASE WHEN BBB.SALESCHANNEL = 'WB' THEN LOWER(TRIM(GA.GA_DEVICE)) ELSE NULL END AS DEVICE,
            CASE WHEN BBB.SALESCHANNEL = 'WB' THEN LOWER(TRIM(BBB.TOPLEVELCATEGORY)) ELSE NULL END AS TOPLEVELCATEGORY,
            BBB.ORDERS,
            BBB.REVENUE_NET_LCL,
            BBB.REVENUE_NET_USD,
            FOREX_RATE.RATE * ZEROIFNULL(REVENUE_NET_LCL) AS REVENUE_NET_USD_CONS_CURR,
            --FTB KPIs
            BBB.FTBS,
            BBB.FTB_REVENUE_NET_LCL,
            BBB.FTB_REVENUE_NET_USD ,
            FOREX_RATE.RATE * ZEROIFNULL(FTB_REVENUE_NET_LCL) AS FTB_REVENUE_NET_USD_CONS_CURR,
    
            --LINE ITEMS AND UNITS
            BBB.PRODUCT_REVENUE_LCL,
            FOREX_RATE.RATE * ZEROIFNULL(PRODUCT_REVENUE_LCL) AS PRODUCT_REVENUE_USD_CONS_CURR,
            BBB.PRODUCTS,
            BBB.QUANTITY,
            DISCOUNT_LCL,
            FOREX_RATE.RATE * ZEROIFNULL(DISCOUNT_LCL) AS DISCOUNT_USD_CONS_CURR,
            CASE WHEN DISCOUNT_FLAG>0 THEN CAST(BBB.ORDERNUMBER AS STRING) ELSE NULL END AS DISCOUNTED_ORDER,
    
    
            -- COSTS
            BBB.ITEMCOST_LCL,
            BBB.ITEMCOST_USD,
            FOREX_RATE.RATE * ZEROIFNULL(BBB.ITEMCOST_LCL) AS ITEMCOST_USD_CONS_CURR,
    
            --GROSS MARGIN
            BBB.GROSS_MARGIN_LCL,
            BBB.GROSS_MARGIN_USD,
    
            --Keep only 1 ROW per TX,BBSTATUS
            ROW_NUMBER() OVER (PARTITION BY ORIGSYSREF, BBSTATUS, BOOKINGDATE ORDER BY BOOKINGDATE DESC) AS RN
            
      FROM 
          ( SELECT * FROM ECOMM_ANALYTICS.ECOMM_KPI_DEV.ECA_WEB_BBB_UNION_VW WHERE BOOKINGDATE<CURRENT_DATE) BBB
      LEFT OUTER JOIN
        ( SELECT * FROM ECOMM_ANALYTICS.ECOMM_KPI_DEV.GA3_GA4_TRANSAC_VW WHERE TRANSACTION_ID IS NOT NULL) GA 
      ON 
            LOWER(TRIM(BBB.ORIGSYSREF)) = LOWER(TRIM(GA.TRANSACTION_ID)) 
      
      LEFT OUTER JOIN 
        (SELECT * FROM ECOMM_ANALYTICS.UTILS.CURRENCY_BUDGET_RATES WHERE FY= 2026)  AS FOREX_RATE
      ON
            FOREX_RATE.CURRENCY_FROM = BBB.CURRENCYCODE 
        )
        WHERE RN=1
    );




----view to showcase lndc and datadriven number for individual orders in a single row
--joining both the tables
CREATE OR REPLACE VIEW GA360_DEV.MTA_LNDC_ORDER_LEVEL_DATA_VW AS
(
WITH MTA_ROLLED_UP AS
(
SELECT  ORIGSYSREF,
        BBSTATUS,
        FTBIND,
        ORDERDATE,
        COUNTRYCODE,
        ORDERS,
        REVENUE_NET_USD_CONS_CURR,
        SALESCHANNEL,
        TP_DATE,
        TX_DEVICE,
        CHANNELS,
        SOURCE,
        MEDIUM,
        CAMPAIGN,
        SUM("Normalized_coeff") AS DD_MARGINAL_ORDERS,
        SUM("Normalized_Revenue") AS DD_MARGINAL_REVENUE,
FROM GA360_DEV.MTA_ORDER_LEVEL_DATA
-- WHERE COUNTRYCODE = 'US' AND ORDERDATE >= '2025-11-01'
-- AND ORIGSYSREF = 'ONNH5NT-71H57-7F5'
-- AND BBSTATUS = 'UPDATE'
GROUP BY ALL
)
,BASE_CTE AS
(
    SELECT
        A.*,
        B.CHANNEL_L1 AS LNDC_CHANNEL
    FROM MTA_ROLLED_UP A
    LEFT OUTER JOIN
    (
        SELECT
            ORIGSYSREF,
            BBSTATUS,
            COUNTRY,
            BOOKINGDATE,
            REVENUE_NET_USD_CONS_CURR,
            ORDERS,
            MAX(CHANNEL_L1) AS CHANNEL_L1
        FROM GA360_DEV.LNDC_ORDER_LEVEL_DATA
        GROUP BY
            ORIGSYSREF,
            BBSTATUS,
            COUNTRY,
            BOOKINGDATE,
            REVENUE_NET_USD_CONS_CURR,
            ORDERS
    ) B
        ON A.ORIGSYSREF = B.ORIGSYSREF
       AND A.BBSTATUS = B.BBSTATUS
       AND A.ORDERDATE = B.BOOKINGDATE
       AND A.COUNTRYCODE = B.COUNTRY
       AND A.REVENUE_NET_USD_CONS_CURR = B.REVENUE_NET_USD_CONS_CURR
       AND A.ORDERS = B.ORDERS
)
,
TP_PER_TX AS
(
SELECT ORIGSYSREF,BBSTATUS,ORDERDATE,COUNT(*) AS FUNNEL_LENGTH
FROM BASE_CTE
GROUP BY ALL
),
FULL_VW AS
(
SELECT A.*, B.FUNNEL_LENGTH
FROM BASE_CTE A LEFT OUTER JOIN TP_PER_TX B
ON A.ORIGSYSREF = B.ORIGSYSREF
AND A.BBSTATUS = B.BBSTATUS
AND A.ORDERDATE = B.ORDERDATE
)
SELECT *,
       ORDERS/FUNNEL_LENGTH AS MARGINAL_ORDERS,
       REVENUE_NET_USD_CONS_CURR/FUNNEL_LENGTH AS MARGINAL_REVENUE
       FROM FULL_VW ORDER BY 1,2
);
